name: 'Puah Image to ECR'
description: 'todo'
author: 'Keboola'
inputs: 
  app_id:
    description: 'App'
    required: true
  tag:
    description: 'Tag'
    required: true
  config_id:
    description: 'Config ID'
    required: true
  storage_token:
    description: 'Storage Token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.app_id }}
    - ${{ inputs.tag }}
    - ${{ inputs.config_id }}
    - ${{ inputs.storage_token }}
